"""adiciona campos de retorno de etapa

Revision ID: cea7b83a8457
Revises: de77a42fede1
Create Date: 2026-09-02 09:02:10.674402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea7b83a8457'
down_revision = 'de77a42fede1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retornado_por', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_retorno', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motivo_retorno', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.drop_column('motivo_retorno')
        batch_op.drop_column('data_retorno')
        batch_op.drop_column('retornado_por')

    # ### end Alembic commands ###
